apiVersion: v1
kind: Namespace
metadata:
  name: kubedl
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubedl-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kubedl-manager-role
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - xdl.kubedl.io
  resources:
  - xdljobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - xdl.kubedl.io
  resources:
  - xdljobs/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - xgboostjob.kubeflow.org
  resources:
  - xgboostjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - xgboostjob.kubeflow.org
  resources:
  - xgboostjobs/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - configmaps
  - events
  - persistentvolumeclaims
  - persistentvolumes
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps.kruise.io
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - kubedl.io
  resources:
  - marsjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubedl.io
  resources:
  - marsjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticdl.org
  resources:
  - elasticdljobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticdl.org
  resources:
  - elasticdljobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - model.kubedl.io
  resources:
    - models
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - model.kubedl.io
  resources:
    - models/status
  verbs:
    - get
- apiGroups:
    - model.kubedl.io
  resources:
    - models/status
  verbs:
    - get
- apiGroups:
    - model.kubedl.io
  resources:
    - modelversions
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - model.kubedl.io
  resources:
    - modelversions/status
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: kubedl-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedl-manager-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kubedl-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedl
  namespace: kubedl-system
  labels:
    app: kubedl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedl
  template:
    metadata:
      labels:
        app: kubedl
    spec:
      containers:
      - image: kubedl/kubedl:v0.1.0
        imagePullPolicy: Always
        name: kubedl-manager
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 2048m
            memory: 2Gi
          requests:
            cpu: 1024m
            memory: 1Gi
      terminationGracePeriodSeconds: 10
